---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-postgres-persistentvolume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  storageClassName: awx-postgres-storageclass
  hostPath:
    path: /srv/postgres-13

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-projects-persistentvolume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  storageClassName: awx-projects-storageclass
  hostPath:
    path: /srv/projects
