---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-projects-persistentvolumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: awx-projects-storageclass
